Added safelisting to the process tree creation flow
CybercentreCanada/assemblyline-v4-service pull request #166
Opened 2021-12-14 21:47 UTC by vipj

Added all functions required to remove safelisted branches from process trees when they are created

2021-12-15 14:01 UTC, cccs-kevin requested changes

2021-12-15 14:01 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +    def _remove_safe_roots(process_tree: List[Dict[str, Any]], process_tree_hashes: List[str], safe_process_tree_hashes: Dict[str, Dict[str, Any]]) -> None:
this method is no longer used, please remove with associated test method

2021-12-16 18:48 UTC, cccs-kevin requested changes

2021-12-16 18:48 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +
this extra new line is not compliant with PEP 8 stylings

2021-12-16 18:48 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +        path = sub(rf"{rule['regex']}", rule['replacement'], path)
unnecessary space

2021-12-17 17:58 UTC, cccs-kevin requested changes

2021-12-17 17:58 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +        :param hash_type: A string representing what type of processing we are doing (root vs leaf)
cut

2021-12-17 17:58 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +        :return: A list of strings representing hashes, in the same order as the provided process tree
update

2021-12-17 17:58 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +            leaf_hashes (List[str]): A list of strings representing hashes of each branch in the process tree
wrong type and def

2021-12-17 17:58 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +    def _remove_safe_leaves_helper(node: Dict[str, Any], leaf_hashes: List[str], safe_leaf_hashes: List[str]) -> Union[str, None]:
leaf_hashes is wrong type

2021-12-17 17:58 UTC, cccs-kevin commented on assemblyline_v4_service/common/dynamic_service_helper.py
> +            leaf_hashes (List[str]): The hashes of all of the leaves in the tree
update_type and def

2021-12-17 20:01 UTC, cccs-kevin approved these changes
TODO: make tests less text-heavy

2022-01-05 20:59 UTC, cccs-kevin commented
Closes https://cccs.atlassian.net/browse/AL-1336
Incoming PR https://github.com/CybercentreCanada/assemblyline-service-cuckoo/pull/137 requires this to be merged first.

2022-01-05 21:05 UTC, cccs-kevin commented
Note that tests passed in dev merge. Pipeline issue is due to this PR being made before the dev PR

2022-01-06 18:49 UTC, cccs-rs approved these changes

2022-01-06 18:50 UTC, merged