add keytool_parse to assemblyline-v4-service instead of assemblyline-…
CybercentreCanada/assemblyline-v4-service pull request #35
Opened 2021-04-08 14:57 UTC by cccs-dawson

Move keytool_parse--see [assemblyline-base PR](https://github.com/CybercentreCanada/assemblyline-base/pull/169)

2021-04-13 12:05 UTC, cccs-rs commented
Might be a good idea to change the Dockerfile to include the installation for keytool since the base image doesn't currently contain it.

From APKaye Dockerfile:
```
# The following line fix an issue with openjdk installation
RUN mkdir -p /usr/share/man/man1

# Get required apt packages
RUN apt-get install -y openjdk-8-jre-headless java-common
```

Then we could remove those similar lines from the related services' Dockerfiles (namely APKaye and Espresso)

2021-04-14 14:05 UTC, cccs-kevin requested changes

2021-04-14 14:05 UTC, cccs-kevin commented on assemblyline_v4_service/common/keytool_parse.py
> +    for cert_str in  re.split('Certificate\[\d+\]:', printcert): # split printcert output incase of certificate chain
`re.split(...) -> split(...)` once the import is changed

2021-04-14 14:05 UTC, cccs-kevin commented on assemblyline_v4_service/common/keytool_parse.py
> +    for cert_str in  re.split('Certificate\[\d+\]:', printcert): # split printcert output incase of certificate chain
`for cert_str in  re.split -> for cert_str in re.split` (remove extra whitespace between `in` and `re.split`)

2021-04-14 14:05 UTC, cccs-kevin commented on assemblyline_v4_service/common/keytool_parse.py
> +            if "Owner:" in line:
is it possible for a line to have `Owner:`, `Issuer:` and `Valid from:` in it? If not then these consecutive `if` statements should be converted to `if, elif, elif`

2021-04-14 14:06 UTC, cccs-kevin commented
> 
> 
> Might be a good idea to change the Dockerfile to include the installation for keytool since the base image doesn't currently contain it.
> 
> From APKaye Dockerfile:
> 
> ```
> # The following line fix an issue with openjdk installation
> RUN mkdir -p /usr/share/man/man1
> 
> # Get required apt packages
> RUN apt-get install -y openjdk-8-jre-headless java-common
> ```
> 
> Then we could remove those similar lines from the related services' Dockerfiles (namely APKaye and Espresso)

Doesn't that make every service more heavyweight though?

2021-04-14 14:14 UTC, cccs-rs commented
> > Might be a good idea to change the Dockerfile to include the installation for keytool since the base image doesn't currently contain it.
> > From APKaye Dockerfile:
> > ```
> > # The following line fix an issue with openjdk installation
> > RUN mkdir -p /usr/share/man/man1
> > 
> > # Get required apt packages
> > RUN apt-get install -y openjdk-8-jre-headless java-common
> > ```
> > 
> > 
> > Then we could remove those similar lines from the related services' Dockerfiles (namely APKaye and Espresso)
> 
> Doesn't that make every service unnecessarily more heavyweight though?

This is true, I guess it has to be noted somewhere that if a service wants to call keytool_parse.keytool_printcert() they need to have the library installed.

2021-04-14 14:16 UTC, cccs-kevin commented
> 
> 
> > > Might be a good idea to change the Dockerfile to include the installation for keytool since the base image doesn't currently contain it.
> > > From APKaye Dockerfile:
> > > ```
> > > # The following line fix an issue with openjdk installation
> > > RUN mkdir -p /usr/share/man/man1
> > > 
> > > # Get required apt packages
> > > RUN apt-get install -y openjdk-8-jre-headless java-common
> > > ```
> > > 
> > > 
> > > Then we could remove those similar lines from the related services' Dockerfiles (namely APKaye and Espresso)
> > 
> > 
> > Doesn't that make every service unnecessarily more heavyweight though?
> 
> This is true, I guess it has to be noted somewhere that if a service wants to call something in keytool_parse they need to have the library installed.

We can just throw the sample Docker command in a docstring in `keytool_parse` and hopefully service developers read through the tools that they are trying to use haha

2021-04-14 15:03 UTC, cccs-kevin commented
unit testing script for tool incoming 🚀

2021-04-15 13:05 UTC, cccs-sgaron commented
Well then if only one service use this why is this not just part of that service?

2021-05-06 17:58 UTC, cccs-dawson commented
this module is here and not in the espresso service because the apkaye service also uses keytool to parse the apks certificate, so it to could use this module

2021-05-17 18:37 UTC, cccs-rs commented
Since keytool_parse is only used by a small subset of current services, we're electing to not make this part of the base service image (otherwise other services will be carrying unneeded bloat). 

Implementation will have to move to the specific service(s) that will use it, namely at the moment APKaye and Espresso.

2021-05-18 11:32 UTC, cccs-rs commented
Seems this PR makes no changes to the Dockerfile which was the initial concern. 

Since there's only been a module addition, I see no reason for this to not be a common module for services (although there should be a note somewhere that the service needs to have keytool installed to leverage this module)

2021-05-18 13:12 UTC, cccs-rs approved these changes

2021-05-18 13:18 UTC, cccs-kevin approved these changes

2021-05-18 13:33 UTC, merged