Fixed bug with Azure DevOps unable to pull Yara rules
CybercentreCanada/assemblyline-v4-service pull request #457
Opened 2022-11-10 14:16 UTC by cccs-sgaron

Azure DevOps does not end its repos with ".git", which caused an issue when trying to pull down Yara rules.

2022-11-15 16:29 UTC, cccs-rs approved these changes

2022-11-15 17:42 UTC, cccs-rs requested changes

2022-11-30 17:30 UTC, C-Oliver commented on assemblyline_v4_service/updater/updater.py
> +                            url_download(source, old_update_time, self.log, update_dir)
Good catch. fixed.

2022-12-01 13:57 UTC, cccs-rs approved these changes

2022-12-06 13:42 UTC, merged